name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go 1.18.6
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: '1.18.6'

      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Set up environment
        run : |
          sudo apt-get update
          sudo apt-get install gcc libc-dev bash perl curl make
          
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          res="$(goimports -l .)"
          if [[ "$(printf '%s' "$res")" != '' ]]; then
            echo "Unformatted source code:"
            echo "$res"
            exit 1
          fi

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test ./...

      - uses: dominikh/staticcheck-action@29e9b80fb8de0521ba4ed3fdf68fed5bbe82a2d2
        with:
          version: "2022.1.1"
          install-go: false

      - name: Build
        run: |
          make

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: l3afd-latest-linux-x86_64
          path: l3afd
