name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17-alpine3.16
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Set up environment
        run : |
          apk update
          apk add gcc libc-dev bash perl curl make
          
      - name: Checkout repository
        uses: actions/checkout@e6d535c99c374d0c3f6d8cd8086a57b43c6c700a

      - name: Format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest      
          res="$(goimports -l .)"
          if [[ "$(printf '%s' "$res")" != '' ]]; then
            echo "Unformatted source code:"
            echo "$res"
            exit 1
          fi
 
      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test ./...

      - uses: dominikh/staticcheck-action@4ec9a0dff54be2642bc76581598ba433fd8d4967
        with:
          version: "2021.1.2"
          install-go: false

      - name: Build
        run: |
          make
