name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go 1.18.6
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: '1.18.6'

      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Set up environment
        run : |
          sudo apt-get update
          sudo apt-get install gcc libc-dev bash perl curl make
          
      - name: Checkout repository
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          res="$(goimports -l .)"
          if [[ "$(printf '%s' "$res")" != '' ]]; then
            echo "Unformatted source code:"
            echo "$res"
            exit 1
          fi

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test ./...

      - uses: dominikh/staticcheck-action@29e9b80fb8de0521ba4ed3fdf68fed5bbe82a2d2
        with:
          version: "2022.1.1"
          install-go: false

      - name: Build
        run: |
          make

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: l3afd-latest-linux-x86_64
          path: l3afd
